package com.kagi.summarizer

// Available Kagi Summarizer languages
val SUMMARY_LANGUAGES = linkedMapOf(
    "Default" to "",
    "Bulgarian" to "BG",
    "Chinese (simplified)" to "ZH",
    "Chinese (traditional)" to "ZH-HANT",
    "Czech" to "CS",
    "Danish" to "DA",
    "Dutch" to "NL",
    "English" to "EN",
    "Estonian" to "ET",
    "Finnish" to "FI",
    "French" to "FR",
    "German" to "DE",
    "Greek" to "EL",
    "Hungarian" to "HU",
    "Indonesian" to "ID",
    "Italian" to "IT",
    "Japanese" to "JA",
    "Korean" to "KO",
    "Latvian" to "LV",
    "Lithuanian" to "LT",
    "Norwegian" to "NB",
    "Polish" to "PL",
    "Portuguese" to "PT",
    "Romanian" to "RO",
    "Russian" to "RU",
    "Slovak" to "SK",
    "Slovenian" to "SL",
    "Spanish" to "ES",
    "Swedish" to "SV",
    "Turkish" to "TR",
    "Ukrainian" to "UK",

    )

val TRANSLATE_LANGUAGES = listOf(
    "Automatic",
    "Abkhaz",
    "Acehnese",
    "Acholi",
    "Afar",
    "Afrikaans",
    "Albanian",
    "Alur",
    "Amharic",
    "Arabic",
    "Armenian",
    "Assamese",
    "Avar",
    "Awadhi",
    "Aymara",
    "Azerbaijani",
    "Balinese",
    "Baluchi",
    "Bambara",
    "Baoulé",
    "Bashkir",
    "Basque",
    "Batak Karo",
    "Batak Simalungun",
    "Batak Toba",
    "Belarusian",
    "Bemba",
    "Bengali",
    "Betawi",
    "Bhojpuri",
    "Bikol",
    "Bosnian",
    "Breton",
    "Bulgarian",
    "Buryat",
    "Cantonese",
    "Catalan",
    "Cebuano",
    "Chamorro",
    "Chechen",
    "Chichewa",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Chuukese",
    "Chuvash",
    "Corsican",
    "Crimean Tatar",
    "Croatian",
    "Czech",
    "Danish",
    "Dari",
    "Dhivehi",
    "Dinka",
    "Dogri",
    "Dombe",
    "Dutch",
    "Dyula",
    "Dzongkha",
    "English",
    "Esperanto",
    "Estonian",
    "Ewe",
    "Faroese",
    "Fijian",
    "Filipino",
    "Finnish",
    "Fon",
    "French",
    "Frisian",
    "Friulian",
    "Fulani",
    "Ga",
    "Galician",
    "Georgian",
    "German",
    "Greek",
    "Guarani",
    "Gujarati",
    "Haitian Creole",
    "Hakha Chin",
    "Hausa",
    "Hawaiian",
    "Hebrew",
    "Hiligaynon",
    "Hindi",
    "Hmong",
    "Hungarian",
    "Hunsrik",
    "Iban",
    "Icelandic",
    "Igbo",
    "Ilocano",
    "Indonesian",
    "Irish",
    "Italian",
    "Jamaican Patois",
    "Japanese",
    "Javanese",
    "Jingpo",
    "Kalaallisut",
    "Kannada",
    "Kanuri",
    "Kapampangan",
    "Kazakh",
    "Khasi",
    "Khmer",
    "Kiga",
    "Kikongo",
    "Kinyarwanda",
    "Kituba",
    "Kokborok",
    "Komi",
    "Konkani",
    "Korean",
    "Krio",
    "Kurdish (Kurmanji)",
    "Kurdish (Sorani)",
    "Kyrgyz",
    "Lao",
    "Latgalian",
    "Latin",
    "Latvian",
    "Ligurian",
    "Limburgish",
    "Lingala",
    "Lithuanian",
    "Lombard",
    "Luganda",
    "Luo",
    "Luxembourgish",
    "Macedonian",
    "Madurese",
    "Maithili",
    "Makassar",
    "Malagasy",
    "Malay",
    "Malay (Jawi)",
    "Malayalam",
    "Maltese",
    "Mam",
    "Manx",
    "Maori",
    "Marathi",
    "Marshallese",
    "Marwadi",
    "Mauritian Creole",
    "Meadow Mari",
    "Meiteilon (Manipuri)",
    "Minang",
    "Mizo",
    "Mongolian",
    "Myanmar (Burmese)",
    "Nahuatl (Eastern Huasteca)",
    "Ndau",
    "Ndebele (South)",
    "Nepalbhasa (Newari)",
    "Nepali",
    "NKo",
    "Norwegian",
    "Nuer",
    "Occitan",
    "Odia (Oriya)",
    "Oromo",
    "Ossetian",
    "Pangasinan",
    "Papiamento",
    "Pashto",
    "Persian",
    "Polish",
    "Portuguese (Brazil)",
    "Portuguese (Portugal)",
    "Punjabi (Gurmukhi)",
    "Punjabi (Shahmukhi)",
    "Quechua",
    "Qʼeqchiʼ",
    "Romani",
    "Romanian",
    "Rundi",
    "Russian",
    "Sami (North)",
    "Samoan",
    "Sango",
    "Sanskrit",
    "Santali",
    "Scots Gaelic",
    "Sepedi",
    "Serbian",
    "Sesotho",
    "Seychellois Creole",
    "Shan",
    "Shona",
    "Sicilian",
    "Silesian",
    "Sindhi",
    "Sinhala",
    "Slovak",
    "Slovenian",
    "Somali",
    "Spanish",
    "Sundanese",
    "Susu",
    "Swahili",
    "Swati",
    "Swedish",
    "Tahitian",
    "Tajik",
    "Tamazight",
    "Tamazight (Tifinagh)",
    "Tamil",
    "Tatar",
    "Telugu",
    "Tetum",
    "Thai",
    "Tibetan",
    "Tigrinya",
    "Tiv",
    "Tok Pisin",
    "Tongan",
    "Tsonga",
    "Tswana",
    "Tulu",
    "Tumbuka",
    "Turkish",
    "Turkmen",
    "Tuvan",
    "Twi",
    "Udmurt",
    "Ukrainian",
    "Urdu",
    "Uyghur",
    "Uzbek",
    "Venda",
    "Venetian",
    "Vietnamese",
    "Waray",
    "Welsh",
    "Wolof",
    "Xhosa",
    "Yakut",
    "Yiddish",
    "Yoruba",
    "Yucatec Maya",
    "Zapotec",
    "Zulu",
)